export const PATHS = {
  DASHBOARD: 'dashboard',
  AUTH: 'auth',
  PROFILE: 'profile',
  GITHUB_PROFILE: 'github-profile',
  SIGN_UP: 'sign-up',
  SIGN_IN: 'sign-in',
  SIGN_IN_TEMPLATE_DRIVEN: 'sign-in-template-driven',
  FORGOT_PASSWORD: 'forgot-password',
  NEW_PASSWORD: 'new-password',
  TWO_STEPS: 'two-steps',
  ERRORS: 'errors',
  ERROR_404: '404',
  ERROR_500: '500',
  FEATURES_UI: 'features/ui',
  FEATURES_TABLE: 'table',
  DOWNLOAD: 'download',
  GIFT: 'gift',
  USERS: 'users',
  SETTINGS: 'settings',
  NOTIFICATIONS: 'gift',
  FOLDERS: 'folders',
  FOLDERS_CURRENT_FILES: 'current-files',
  FOLDERS_DOWNLOAD: 'download',
  FOLDERS_TRASH: 'trash',
};
