name: Build and Deploy to DigitalOcean

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'libs/**'

jobs:
  deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build API with Nx
        run: pnpm exec nx run api:build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install doctl
        run: |
          sudo snap install doctl
          doctl auth init -t ${{ secrets.DOCKER_PASSWORD }}

      - name: Clean Up DigitalOcean Registry
        run: |
          REPO="admin-api"
          TAGS=$(doctl registry repository list-tags $REPO --format Tag --no-header)
          for TAG in $TAGS; do
            echo "Deleting tag: $TAG"
            doctl registry repository delete-tag $REPO $TAG --force
          done

      - name: Build Docker Image
        run: docker build -t registry.digitalocean.com/admin-api-registry-v1/admin-api:latest -f apps/api/Dockerfile .

      - name: Push Docker Image
        run: docker push registry.digitalocean.com/admin-api-registry-v1/admin-api:latest
