name: Test DigitalOcean Registry Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup:
    name: Clean DigitalOcean Registry (All Images)
    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        run: |
          sudo snap install doctl
          doctl auth init -t ${{ secrets.DOCKER_PASSWORD }}

      - name: Delete all images (tagged and untagged) from DigitalOcean Registry
        run: |
          REPO="admin-api"
          DIGESTS=$(doctl registry repository list-manifests $REPO --format Digest --no-header)
          for DIGEST in $DIGESTS; do
            echo "Deleting digest: $DIGEST"
            doctl registry repository delete-manifest $REPO $DIGEST --force
          done
